services:
  roster:
    image: ghcr.io/dorbian/roster:latest
    container_name: game-roster
    restart: unless-stopped
    environment:
      ROSTER_HOSTNAME: roster.thebigtree.life
      ROSTER_DATA_DIR: /data
      PORT: "8500"
    expose:
      - "8500"
    volumes:
      - /opt/groster/data:/data:Z
    networks:
      - honsefarm

networks:
  honsefarm:
    external: true
